name: Deploy to Kinsta

on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || github.ref == 'refs/heads/staging' && 'Staging' || github.ref == 'refs/heads/development' && 'Development' }}

    steps:
      # Checkout the latest code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add SSH Key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Deploy
        id: deploy_files
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.SSH_KEY}}
        with:
          flags: '-acvzrW --human-readable'
          src: './test'
          dest: '${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/html/test-ssh'
